# Generated by Django 4.0.2 on 2022-04-06 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Город',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb', models.URLField(blank=True, null=True, verbose_name='Фейсбук')),
                ('vk', models.URLField(blank=True, null=True, verbose_name='ВКонтакте')),
                ('inst', models.URLField(blank=True, null=True, verbose_name='Инстаграм')),
                ('site', models.URLField(blank=True, null=True, verbose_name='Сайт')),
                ('phone', models.TextField(blank=True, null=True, verbose_name='Телефон')),
                ('phone1', models.TextField(blank=True, null=True, verbose_name='Доп. телефон')),
                ('phone2', models.TextField(blank=True, null=True, verbose_name='Доп. телефон')),
                ('phone3', models.TextField(blank=True, null=True, verbose_name='Доп. телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта')),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Области',
                'verbose_name_plural': 'Области',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='place_image/', verbose_name='Изображение')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображение',
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Сезоны',
                'verbose_name_plural': 'Сезоны',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Тег',
            },
        ),
        migrations.CreateModel(
            name='TimeOfWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday_start', models.TimeField(blank=True, null=True, verbose_name='Начало приема заказов в понедельник')),
                ('monday_end', models.TimeField(blank=True, null=True, verbose_name='Окончание приема заказов в понедельник')),
                ('monday_is_day_off', models.BooleanField(default=False, verbose_name='Понедельник выходной?')),
                ('tuesday_start', models.TimeField(blank=True, null=True, verbose_name='Начало приема заказов во вторник')),
                ('tuesday_end', models.TimeField(blank=True, null=True, verbose_name='Окончание приема заказов во вторник')),
                ('tuesday_is_day_off', models.BooleanField(default=False, verbose_name='Вторник выходной?')),
                ('wednesday_start', models.TimeField(blank=True, null=True, verbose_name='Начало приема заказов в среду')),
                ('wednesday_end', models.TimeField(blank=True, null=True, verbose_name='Окончание приема заказов в среду')),
                ('wednesday_is_day_off', models.BooleanField(default=False, verbose_name='Среда выходной?')),
                ('thursday_start', models.TimeField(blank=True, null=True, verbose_name='Начало приема заказов в четверг')),
                ('thursday_end', models.TimeField(blank=True, null=True, verbose_name='Окончание приема заказов в четверг')),
                ('thursday_is_day_off', models.BooleanField(default=False, verbose_name='Четверг выходной?')),
                ('friday_start', models.TimeField(blank=True, null=True, verbose_name='Начало приема заказов в пятницу')),
                ('friday_end', models.TimeField(blank=True, null=True, verbose_name='Окончание приема заказов в пятницу')),
                ('friday_is_day_off', models.BooleanField(default=False, verbose_name='Пятница выходной?')),
                ('saturday_start', models.TimeField(blank=True, null=True, verbose_name='Начало приема заказов в субботу')),
                ('saturday_end', models.TimeField(blank=True, null=True, verbose_name='Окончание приема заказов в субботу')),
                ('saturday_is_day_off', models.BooleanField(default=False, verbose_name='Суббота выходной?')),
                ('sunday_start', models.TimeField(blank=True, null=True, verbose_name='Начало приема заказов в воскресенье')),
                ('sunday_end', models.TimeField(blank=True, null=True, verbose_name='Окончание приема заказов в воскресенье')),
                ('sunday_is_day_off', models.BooleanField(default=False, verbose_name='Воскресенье выходной?')),
            ],
            options={
                'verbose_name': 'Время работы',
                'verbose_name_plural': 'Время работы',
            },
        ),
        migrations.CreateModel(
            name='TypePlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип места',
                'verbose_name_plural': 'Тип места',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Место')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адрес')),
                ('coordinates', models.TextField(verbose_name='Координаты')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Цена')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='place.city', verbose_name='Город')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='place.contact', verbose_name='Контакты')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.district', verbose_name='Район')),
                ('image', models.ManyToManyField(blank=True, to='place.Image', verbose_name='Изображения')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.season', verbose_name='Сезон')),
                ('tag', models.ManyToManyField(blank=True, to='place.Tag', verbose_name='Тэги')),
                ('time', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='place.timeofwork', verbose_name='Время работы')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.typeplace', verbose_name='Тип места')),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Место',
            },
        ),
    ]
