# Generated by Django 4.0.2 on 2022-03-01 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb', models.URLField(blank=True, null=True, verbose_name='Фейсбук')),
                ('vk', models.URLField(blank=True, null=True, verbose_name='ВКонтакте')),
                ('inst', models.URLField(blank=True, null=True, verbose_name='Инстаграм')),
                ('site', models.URLField(blank=True, null=True, verbose_name='Сайт')),
                ('phone', models.TextField(blank=True, null=True, verbose_name='Телефон')),
                ('phone1', models.TextField(blank=True, null=True, verbose_name='Доп. телефон')),
                ('phone2', models.TextField(blank=True, null=True, verbose_name='Доп. телефон')),
                ('phone3', models.TextField(blank=True, null=True, verbose_name='Доп. телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта')),
            ],
        ),
        migrations.CreateModel(
            name='TimeOfWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday_start', models.TimeField(blank=True, null=True, verbose_name='Начало приема заказов в понедельник')),
                ('monday_end', models.TimeField(blank=True, null=True, verbose_name='Окончание приема заказов в понедельник')),
                ('monday_is_day_off', models.BooleanField(default=False, verbose_name='Понедельник выходной?')),
                ('tuesday_start', models.TimeField(blank=True, null=True, verbose_name='Начало приема заказов во вторник')),
                ('tuesday_end', models.TimeField(blank=True, null=True, verbose_name='Окончание приема заказов во вторник')),
                ('tuesday_is_day_off', models.BooleanField(default=False, verbose_name='Вторник выходной?')),
                ('wednesday_start', models.TimeField(blank=True, null=True, verbose_name='Начало приема заказов в среду')),
                ('wednesday_end', models.TimeField(blank=True, null=True, verbose_name='Окончание приема заказов в среду')),
                ('wednesday_is_day_off', models.BooleanField(default=False, verbose_name='Среда выходной?')),
                ('thursday_start', models.TimeField(blank=True, null=True, verbose_name='Начало приема заказов в четверг')),
                ('thursday_end', models.TimeField(blank=True, null=True, verbose_name='Окончание приема заказов в четверг')),
                ('thursday_is_day_off', models.BooleanField(default=False, verbose_name='Четверг выходной?')),
                ('friday_start', models.TimeField(blank=True, null=True, verbose_name='Начало приема заказов в пятницу')),
                ('friday_end', models.TimeField(blank=True, null=True, verbose_name='Окончание приема заказов в пятницу')),
                ('friday_is_day_off', models.BooleanField(default=False, verbose_name='Пятница выходной?')),
                ('saturday_start', models.TimeField(blank=True, null=True, verbose_name='Начало приема заказов в субботу')),
                ('saturday_end', models.TimeField(blank=True, null=True, verbose_name='Окончание приема заказов в субботу')),
                ('saturday_is_day_off', models.BooleanField(default=False, verbose_name='Суббота выходной?')),
                ('sunday_start', models.TimeField(blank=True, null=True, verbose_name='Начало приема заказов в воскресенье')),
                ('sunday_end', models.TimeField(blank=True, null=True, verbose_name='Окончание приема заказов в воскресенье')),
                ('sunday_is_day_off', models.BooleanField(default=False, verbose_name='Воскресенье выходной?')),
            ],
        ),
    ]
