# Generated by Django 4.0.2 on 2022-04-06 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeofwork',
            name='friday_end',
        ),
        migrations.RemoveField(
            model_name='timeofwork',
            name='friday_is_day_off',
        ),
        migrations.RemoveField(
            model_name='timeofwork',
            name='friday_start',
        ),
        migrations.RemoveField(
            model_name='timeofwork',
            name='monday_end',
        ),
        migrations.RemoveField(
            model_name='timeofwork',
            name='monday_is_day_off',
        ),
        migrations.RemoveField(
            model_name='timeofwork',
            name='monday_start',
        ),
        migrations.RemoveField(
            model_name='timeofwork',
            name='saturday_end',
        ),
        migrations.RemoveField(
            model_name='timeofwork',
            name='saturday_is_day_off',
        ),
        migrations.RemoveField(
            model_name='timeofwork',
            name='saturday_start',
        ),
        migrations.RemoveField(
            model_name='timeofwork',
            name='sunday_end',
        ),
        migrations.RemoveField(
            model_name='timeofwork',
            name='sunday_is_day_off',
        ),
        migrations.RemoveField(
            model_name='timeofwork',
            name='sunday_start',
        ),
        migrations.RemoveField(
            model_name='timeofwork',
            name='thursday_end',
        ),
        migrations.RemoveField(
            model_name='timeofwork',
            name='thursday_is_day_off',
        ),
        migrations.RemoveField(
            model_name='timeofwork',
            name='thursday_start',
        ),
        migrations.RemoveField(
            model_name='timeofwork',
            name='tuesday_end',
        ),
        migrations.RemoveField(
            model_name='timeofwork',
            name='tuesday_is_day_off',
        ),
        migrations.RemoveField(
            model_name='timeofwork',
            name='tuesday_start',
        ),
        migrations.RemoveField(
            model_name='timeofwork',
            name='wednesday_end',
        ),
        migrations.RemoveField(
            model_name='timeofwork',
            name='wednesday_is_day_off',
        ),
        migrations.RemoveField(
            model_name='timeofwork',
            name='wednesday_start',
        ),
        migrations.AddField(
            model_name='timeofwork',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Окончание работы'),
        ),
        migrations.AddField(
            model_name='timeofwork',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Начало работы'),
        ),
        migrations.AddField(
            model_name='timeofwork',
            name='weekday',
            field=models.CharField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота'), (7, 'Воскресенье')], default=1, max_length=50, verbose_name='День недели'),
            preserve_default=False,
        ),
    ]
