# Generated by Django 4.0.2 on 2022-04-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_remove_timeofwork_friday_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeofwork',
            name='weekday',
            field=models.CharField(choices=[('1', 'Понедельник'), ('2', 'Вторник'), ('3', 'Среда'), ('4', 'Четверг'), ('5', 'Пятница'), ('6', 'Суббота'), ('7', 'Воскресенье')], max_length=50, verbose_name='День недели'),
        ),
    ]
