# Generated by Django 4.0.2 on 2022-04-08 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0003_alter_timeofwork_weekday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='time',
        ),
        migrations.AddField(
            model_name='timeofwork',
            name='place',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='place.place', verbose_name='Место'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='place',
            name='tag',
            field=models.ManyToManyField(blank=True, to='place.Tag', verbose_name='Теги'),
        ),
    ]
