# Generated by Django 4.0.2 on 2022-04-26 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0005_favouriteplace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favouriteplace',
            name='place',
        ),
        migrations.AddField(
            model_name='favouriteplace',
            name='place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='place.place', verbose_name='Места'),
            preserve_default=False,
        ),
    ]
