# Generated by Django 4.0.2 on 2022-04-06 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_remove_timeofwork_friday_end_and_more'),
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={'verbose_name': 'Тур', 'verbose_name_plural': 'Тур'},
        ),
        migrations.AddField(
            model_name='trip',
            name='place',
            field=models.ManyToManyField(to='place.Place', verbose_name='Места'),
        ),
    ]
