# Generated by Django 4.0.2 on 2022-04-26 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0004_remove_place_time_timeofwork_place_alter_place_tag'),
        ('trip', '0002_alter_trip_options_trip_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertrip',
            name='place',
        ),
        migrations.CreateModel(
            name='UserPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('visit_time', models.TimeField(blank=True, null=True, verbose_name='Время')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.place', verbose_name='Место')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.trip', verbose_name='Тур')),
            ],
        ),
    ]
