# Generated by Django 4.0.2 on 2022-04-28 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0005_remove_favouritetrip_trip_favouritetrip_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplace',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.usertrip', verbose_name='Тур'),
        ),
    ]
