# Generated by Django 4.0.2 on 2022-05-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0006_alter_userplace_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplace',
            name='visit_time',
            field=models.TimeField(blank=True, default=None, null=True, verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='usertrip',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
